kind: Service
apiVersion: v1
metadata:
  name: clarity-service
  namespace: default
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: default
      port: 80
      protocol: TCP
      targetPort: 80
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clarity-service
  labels:
    app: clarity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clarity-service
  template:
    metadata:
      labels:
        app: clarity-service
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: clarity-service
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
